spring:
  application:
    name: payment
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot-mybatis?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样率值介于0到1之间,1则表示全部采集
server:
  port: 8083
eureka:
  instance:
    prefer-ip-address: true
    ip-address: admin.com
    instance-id: ${spring.application.name}-${eureka.instance.ip-address}:${server.port}
    # eureka客户端向服务端发送心跳的时间间隔
    lease-renewal-interval-in-seconds: 10
    # eureka服务端在收到客户端最后一次心跳后等待的时间上限，超时即剔除服务
    lease-expiration-duration-in-seconds: 50
  client:
    service-url:
      defaultZone: http://admin:admin@admin.com:7001/eureka/,http://admin:admin@eurekaServer7002.com:7002/eureka/
mybatis:
  type-aliases-package: com.example.eurekapayment.entity
  mapper-locations: mapper/*.xml