spring:
  application:
    name: customer-hystrix
server:
  port: 8002
eureka:
  instance:
    prefer-ip-address: true
    ip-address: admin.com
    instance-id: ${spring.application.name}-${eureka.instance.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 50
  client:
    service-url:
      defaultZone: http://admin:admin@admin.com:7001/eureka/,http://admin:admin@eurekaServer7002.com:7002/eureka/
#      defaultZone: http://admin:admin@eurekaServer7001:com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
feign:
  hystrix:
    enabled: true