package com.example.eurekaprovider.dao;

import java.util.List;

import com.example.commons.entity.Employee;
import com.example.commons.entity.EmployeeExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

/**
 * @author: guoqing.chen01@hand-china.com 2021-07-14 14:29
 */
@Mapper
public interface EmployeeMapper {

    /**
     * 根据ID查找员工
     * @param id
     * @return
     */
    @Select("select * from employees where employee_id = #{id}")
    Employee findById(Long id);

    List<Employee> findByIds(@Param("ids") List<Long> ids);

    /**
     * 通过动态SQL批量插入数据
     * @param employees
     * @return
     */
    int insertBatch(@Param("employees") List<Employee> employees);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Wed Jul 14 10:17:11 CST 2021
     */
    long countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Wed Jul 14 10:17:11 CST 2021
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Wed Jul 14 10:17:11 CST 2021
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Wed Jul 14 10:17:11 CST 2021
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Wed Jul 14 10:17:11 CST 2021
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Wed Jul 14 10:17:11 CST 2021
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Wed Jul 14 10:17:11 CST 2021
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);
}