server:
  port: 8081
spring:
  application:
    name: provider
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot-mybatis?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunMillis: 60000
    minEvicatableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatement: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#  cloud:
#    inetutils:
#      ignored-interfaces[0]: VirtualBox Host-Only Ethernet Adapter
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eurekaServer7001.com:7001/eureka/,http://admin:admin@eurekaServer7002.com:7002/eureka/
#      defaultZone: http://dev.hzero.org:8000/eureka/
  instance:
    prefer-ip-address: true
#    ip-address: 10.211.169.235
    ip-address: 10.211.96.237
    instance-id: ${spring.application.name}-${eureka.instance.ip-address}:${server.port}
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.eurekaprovider.entity