spring:
  application:
    name: eurekaServer7002
  security:
    user:
      name: admin
      password: admin
server:
  port: 7002
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:admin@admin.com:7001/eureka/
#  server:
#    renewalPercentThreshold: 0.49