spring:
  application:
    name: admin.com
  security:
    user:
      name: admin
      password: admin
server:
  port: 7001
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      # 集群配置，指向其他eureka服务器
      defaultZone: http://admin:admin@eurekaServer7002.com:7002/eureka/
      # 单机配置，指向自己
#       defaultZone: http://admin:admin@admin.com:7001/eureka/
  server:
    # 关闭自我保护
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000