server:
  port: 8802
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@admin.com:7001/eureka/,http://admin:admin@eurekaServer7002.com:7002/eureka/
  instance:
    prefer-ip-address: true
    instance-id: receive8802.com
spring:
  application:
    name: stream-client-consumer8802
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务消息
        defaultRabbit: # 表示定义的名称，用于binding的整合
          type: rabbit # 消息组建类型
          environment: # 设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的真整合处理
        # 服务端为output，客户端为input
#        output: # 通道的名称
         input: # 通道的名称
          destination: studyExchange # 表明使用的Exchange名称定义
          context-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
#          group: exampleA